Vagrant.configure("2") do |config|

  # Box base
  config.vm.box = "ubuntu/bionic64"

  # VM1
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.10"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end
  end

  # VM2
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.11"
    vm2.vm.synced_folder "./MusicasAPI", "/home/vagrant/vagrant_data"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end

    vm2.vm.provision "shell", inline: <<-SHELL
      # Atualiza pacotes
      sudo apt-get update

      # Instala .NET SDK 9.0
      wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y apt-transport-https
      sudo apt-get update
      sudo apt-get install -y dotnet-sdk-9.0

      # Executa API
      cd /home/vagrant/vagrant_data
      dotnet run --urls "http://0.0.0.0:5000" &
    SHELL
  end
end
