name: Build and Run on Pull Request to Main

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MusicasAPI/MusicasAPI

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./MusicasAPI/MusicasAPI

    - name: Run project for 10 seconds
      run: |
        echo "Executando API por 10 segundos..."
        timeout 10 dotnet run --no-build --project ./MusicasAPI/MusicasAPI/MusicasAPI.csproj || echo "Execução finalizada (por timeout)"
